//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicFacebookFeatures.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicFacebookFeatures.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Birthday! 🎉🎂 Wishing you a day filled with joy, laughter, and all the things that make you smile. May this year be filled with unforgettable moments, cherished memories, and endless possibilities. Here&apos;s to you, and to all the amazing adventures that lie ahead! Cheers to another fantastic year of life!.
        /// </summary>
        internal static string GreetType1 {
            get {
                return ResourceManager.GetString("GreetType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Happy Birthday to someone who brings sunshine into the lives of everyone around them! 🎉☀️ May your special day be as bright and beautiful as you are, filled with love, laughter, and unforgettable moments. Here&apos;s to another year of spreading joy and making wonderful memories! Cheers to you!&quot;.
        /// </summary>
        internal static string GreetType2 {
            get {
                return ResourceManager.GetString("GreetType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday Greeting 3:
        ///&quot;Wishing the happiest of birthdays to an incredible soul! 🎂🌟 May this day be a celebration of all the wonderful things that make you unique and loved. Here&apos;s to laughter that fills the air, smiles that light up faces, and happiness that knows no bounds. May the year ahead be even more amazing than the last, filled with love, success, and endless blessings. Cheers to you and the remarkable journey ahead!&quot;.
        /// </summary>
        internal static string GreetType3 {
            get {
                return ResourceManager.GetString("GreetType3", resourceCulture);
            }
        }
    }
}
